[workspace]
resolver = "3"

[package]
name = "cobt2"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
clap = { version = "4.5.45", features = ["derive"] }
proptest = { version = "1.7.0", features = ["attr-macro"] }
rand = "0.9.2"
rand_pcg = "0.9.0"
rayon = "1.11.0"
sim =  { path = "sim" }

[profile.debug-rel]
inherits = "release"
debug = true
